MOCK_ARTICLES = [
    {
        "id": 1,
        "title": "The Tortoise and the Hare",
        "excerpt": "A slow tortoise challenges a boastful hare to a race, and patience proves mightier than speed.",
        "content": "A Hare was one day making fun of a Tortoise for being so slow upon his feet. \"Wait a little,\" said the Tortoise, \"I will run a race with you, and I will wager that I will be the winner.\"\n\nThe Hare agreed, and the race began. The Hare darted almost out of sight at once, but soon stopped to rest, and said: \"There is plenty of time; I will have a good sleep.\" The Tortoise walked quietly on, and when the Hare awoke from his nap, he saw the Tortoise just near the winning-post, and could not run fast enough to overtake him.\n\nThen the Tortoise said: \"Slow and steady wins the race.\"",
        "difficulty": "beginner",
        "tags": ["fable", "classic"],
        "read_time_minutes": 2,
        "created_at": "2026-08-01T09:00:00",
    },
    {
        "id": 2,
        "title": "The Boy Who Cried Wolf",
        "excerpt": "A shepherd boy tricks his village with false alarms until no one believes him when it truly matters.",
        "content": "There was once a boy who kept sheep not far from a village. It was his duty to take care of them, and to give warning when any wolf came near.\n\nOne day he thought he would have some fun at the expense of the villagers, so he cried out with all his might: \"Wolf! Wolf!\" The villagers ran out to help him, but there was no wolf. The boy laughed at their fright. The next day he did it again, and again the villagers came running, only to find no wolf.\n\nNot long after, a wolf really did come. The boy cried out in earnest: \"Wolf! Wolf!\" But the villagers thought he was playing his trick again, and no one came to help. The wolf carried off the sheep. A liar will not be believed, even when he speaks the truth.",
        "difficulty": "beginner",
        "tags": ["fable", "classic"],
        "read_time_minutes": 2,
        "created_at": "2026-08-01T10:00:00",
    },
    {
        "id": 3,
        "title": "The Fox and the Grapes",
        "excerpt": "A hungry fox cannot reach a bunch of grapes and decides they must be sour — the birth of a famous idiom.",
        "content": "One hot summer's day a Fox was strolling through an orchard till he came to a bunch of Grapes just ripening on a vine which had been trained over a lofty branch.\n\n\"Just the thing to quench my thirst,\" quoth he. Drawing back a few paces, he took a run and a jump, and just missed the bunch. Turning round again with a One, Two, Three, he jumped up, but with no greater success. Again and again he tried after the tempting morsel, but at last had to give it up.\n\nWalking away with his nose in the air, he said: \"I am sure they are sour.\" It is easy to despise what you cannot get.",
        "difficulty": "intermediate",
        "tags": ["fable", "idiom"],
        "read_time_minutes": 3,
        "created_at": "2026-08-02T09:00:00",
    },
    {
        "id": 4,
        "title": "The North Wind and the Sun",
        "excerpt": "Wind and Sun compete to make a traveller remove his coat, and gentleness wins over force.",
        "content": "The North Wind and the Sun had a quarrel about which of them was the stronger. While they were disputing with much heat and bluster, a Traveller passed along the road wrapped in a cloak.\n\nThey agreed that the one who could first make the Traveller take his cloak off should be considered stronger than the other. The North Wind tried his power first, blowing a fierce blast, but the harder he blew the more closely did the Traveller wrap his cloak around him.\n\nThen the Sun shone out in all his warmth, and the Traveller soon felt too hot to carry his cloak, and took it off. Kindness works more effectively than force.",
        "difficulty": "intermediate",
        "tags": ["fable", "classic"],
        "read_time_minutes": 3,
        "created_at": "2026-08-02T14:00:00",
    },
]
